datasets:
  cc_sbu_align:
    text_processor:
      train:
        name: blip_caption
    vis_processor:
      train:
        image_size: 224
        name: blip2_image_eval
model:
  arch: mini_gpt4
  ckpt: /work/agoindan/.cache//prerained_minigpt4_7b.pth
  end_sym: '###'
  freeze_qformer: true
  freeze_vit: true
  low_resource: true
  max_txt_len: 160
  model_type: pretrain_vicuna
  prompt_path: /home/agoindan/HEMM/hemm/models/minigpt4/prompts/alignment.txt
  prompt_template: '###Human: {} ###Assistant: '
run:
  task: image_text_pretrain
