# -*- coding: utf-8 -*-
"""NLVR_prompt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWyAX68X9MRAFFQxPd4If7dPRHqsQX81
"""

class nlvrprompt:
  def __init__(self):
       self.prompt=f"""Given this image along with a question about the image,
  please answer the question with only the word 'true' or 'false'.
  Question: {}
  Answer:"""

  def format_prompt(self, text):
        self.prompt = self.prompt.format(text)
        return self.prompt