# -*- coding: utf-8 -*-
"""NLVR2prompt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWyAX68X9MRAFFQxPd4If7dPRHqsQX81
"""

class NLVR2prompt:
  def __init__(self):
       self.prompt="""
        You are given an image and a related text, use the image as context and reply with true or false only
        Text: {}
        Answer:
        """

  def format_prompt(self, text):
        self.prompt = self.prompt.format(text)
        return self.prompt
