# -*- coding: utf-8 -*-
"""NLVR_prompt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWyAX68X9MRAFFQxPd4If7dPRHqsQX81
"""

class nlvrprompt:
  def __init__(self):
       self.prompt="""Given an image and the Question: {}, Answer the question with only 'true' or 'false'. Answer: """

  def format_prompt(self, text):
        prompt_text = self.prompt.format(text)
        return prompt_text
